-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 05 Mar 2023 pada 14.34
-- Versi server: 10.4.22-MariaDB
-- Versi PHP: 8.1.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `uas`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `akun`
--

CREATE TABLE `akun` (
  `id` int(11) NOT NULL,
  `email` varchar(50) NOT NULL,
  `username` varchar(20) NOT NULL,
  `password` varchar(20) NOT NULL,
  `level` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data untuk tabel `akun`
--

INSERT INTO `akun` (`id`, `email`, `username`, `password`, `level`) VALUES
(1, 'admin@admin.com', 'admin', '123', 'admin'),
(2, 'akbarfais06@gmail.com', 'FaisAkbar', '123456789', 'user'),
(110, 'akbarfais13@gmail.com', 'fais063', '123', 'user'),
(111, 'akbarfais15@gmail.com', 'fais15', '1234', 'user'),
(112, 'akbarfais@gmail.com', 'Fais', '123456789', 'user'),
(113, 'akbarfais10@gmail.com', 'Fais', '12345', 'user');

-- --------------------------------------------------------

--
-- Struktur dari tabel `wisata`
--

CREATE TABLE `wisata` (
  `kd_wisata` int(11) NOT NULL,
  `nama_wisata` varchar(100) CHARACTER SET latin1 NOT NULL,
  `gambar` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `gambar_L` varchar(100) CHARACTER SET latin1 NOT NULL,
  `harga_tiket` int(11) NOT NULL,
  `deskripsi_wisata` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `open_closes` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `gmaps` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data untuk tabel `wisata`
--

INSERT INTO `wisata` (`kd_wisata`, `nama_wisata`, `gambar`, `gambar_L`, `harga_tiket`, `deskripsi_wisata`, `open_closes`, `gmaps`) VALUES
(1, 'Masjid Jami\'', 'masjidJami.jpg', 'masjidJami_L.jpg', 5000, 'Wisata Pantai Lombang Sumenep Madura adalah tempat wisata pantai bernilai sejarah yang ada di pulau Madura. Tempat ini cocok sebagai media berlibur dan belajar. Merasakan indahnya pantai sembari belajar sejarah Pantai Lombang di Sumenep Madura dan menambah ilmu pengetahuan alam. Anda yang berwisata beserta buah hati tercinta, Pantai Lombang ini salah satu lokasi yang tepat.\r\nPantai Lombang di Madura memiliki pantai dengan pasir putih dan air laut yang biru. Keunikan yang ada pada pantai ini adalah adanya pepohonan yang berjejer memagari pantai. Pohon yang tumbuh di area Pantai Lombang adalah pohon cemara udang. Pantai Lombang adalah satu-satunya pantai di Indonesia yang ditumbuhi oleh pohon cemara udang. Tidak seperti pohon cemara pada umumnya. Bila pohon cemara memiliki ketinggian yang menjulang dengan bentuk tegak dan tinggi, pohon cemara udang memiliki bentuk pohon yang agak rendah dan melengkunh seperti udang. Oleh sebab itu, pohon cemara jenis ini diberi nama pohon cemara udang. Pohon-pohon cemara tersebut menghilangkan kesan pantai yang biasanya panas. Udara yang mengalir dari pepohonan membuat suasana pantai ini terasa asri dan sejuk.', '07.00 – 18.00 WIB', 'MasjidJamikSumenep'),
(2, 'Bukit Tinggi', 'bukitTinggi.jpg', 'bukitTinggi_L.jpg', 5000, 'Wisata Bukit Tinggi Daramista di Sumenep Madura merupakan tempat wisata yang harus anda kunjungi karena pesona keindahannya tidak ada duanya. Penduduk lokal daerah Wisata Bukit Tinggi Daramista di Sumenep Madura juga sangat ramah tamah terhadap wisatawan lokal maupun wisatawan asing. Kota Sumenep juga terkenal akan Wisata Bukit Tinggi Daramista di Sumenep Madura yang sangat menarik untuk dikunjungi. Wisata Bukit Tinggi Daramista ini memiliki pemandangan yang memukau, lengkap dengan beberapa gubuk-gubuk kecil dan kolam-kolam yang terdapat di sekitar lokasi. Kalau malam hari, kamu juga bisa menikmati gemerlap lampu-lampu kecil yang dilekatkan di atas pepohonan. Suasana romantis yang langsung terasa begitu anda sampai di sini. Tak hanya itu, anda juga bisa memanfaatkan bukit ini untuk menunggu datangnya senja. Dan bila anda mempunyai hobi fotografi, di sini juga disediakan beberapa spot yang kece. Pokoknya kamu nggak bakal nyesel kalau datang ke sini.\r\nDi sini pengunjung dapat menikmati kota Sumenep dari atas Ketinggian, tak hanya itu pengunjung juga bisa melihat moment Matahari Tenggelam dan Terbit dengan bebas. Disekitar bukit terdapat gubuk kecil dan ada sebuah kolam ikan yang masih bernuansa bambu dan cukup menarik perhatian pengunjung. Dari puncak bukit kita juga bisa menikmati senja sore, banyak pengunjung yang memang sengaja datang ke bukit menjelang sore berakhir agar tidak ketinggalan senja yang sangat indah.', '06.00 – 22.00 WIB', 'BoekitTinggiDaramista'),
(3, 'Pantai Sembilan', 'pantaiSembilan.jpg', 'pantaiSembilan_L.jpg', 5000, 'Di dunia wisata Tanah Air, Madura memang belum menjadi tujuan favorit. Pulau yang dijuluki pulau garam ini memang terkenal memiliki cuaca panas yang membuat wisatawan enggan berkunjung. Padahal jika berbicara tentang tempat wisata, Madura banyak punya banyak pilihan, termasuk Pantai Sembilan.\r\n\r\nPantai ini terletak di Desa Bringsang, Kecamatan Gili Genting, Kabupaten Sumenep. Pantai ini merupakan salah satu tempat wisata eksotis dengan bentuk pantainya yang mirip dengan angka sembilan. Keindahan ini semakin menguatkan pendapat bahwa Sumenep merupakan andalan objek wisata setempat. Tak heran jika kabupaten ini disebut sebagai \"The Soul of Madura\".\r\n\r\nKecamatan Gili Genting tempat Pantai Sembilan berada merupakan pulau sendiri yang terletak di sebelah tenggara Pulau Madura. Untuk sampai ke tempat ini, kita harus menyeberangi laut. Dibutuhkan waktu sekitar 30 sampai 45 menit menggunakan perahu motor jika berangkat dari Pelabuhan Tanjung, Saronggi, Sumenep.\r\n\r\nPantai ini dulunya bernama Pantai Bringsang. Karena memiliki bentuk angka sembilan ketika dipotret dari atas, namanya pun diganti menjadi Pantai Sembilan. Dulunya, pantai ini merupakan pelabuhan kecil yang menghubungkan Pulau Gili Genting dengan pulau-pulau di sekitarnya, termasuk Pulau Madura.\r\n\r\nSelain bentuk angka sembilan, pantai ini juga menyuguhkan pemandangan alam yang luar biasa. Pantainya putih bersih dengan deburan ombak yang tidak terlalu keras, plus angin sejuk yang bertiup pelan. Tempat yang cocok untuk menghabiskan waktu bersama keluarga.\r\n\r\nAir laut yang berwarna biru jernih juga menggoda para pengunjung untuk berenang atau bermain air. Buat yang suka snorkeling, pantai ini punya terumbu karang cantik sekaligus unik. Di pantai ini juga sudah ada beberapa spot menarik yang bisa jadi tempat untuk berfoto, termasuk ayunan yang dipasang tepat di bibir pantai. Ada juga penginapan yang dibangun sedemikian rupa, sehingga pengunjung bisa langsung menikmati matahari terbit atau sunrise.', 'Open 24 hours', 'PantaiSembilan,Dadap,Bringsang,Kec.Giligenteng,KabupatenSumenep,JawaTimur'),
(4, 'Asta Tinggi', 'astaTinggi.jpg', 'astaTinggi_L.jpg', 0, 'Asta berarti makam, tinggi berarti bukit. Asta Tinggi merupakan makam para Raja Sumenep dan keturunannya yang berada diatas bukit. Cara menuju asta tinggi diikuti dengan jalan menanjak. Asta tinggi dibangun sekitar tahun 1750 M.\r\n\r\nKetika sampai disana, pengunjung disuguhi dengan pintu masuk berupa dinding besar berwarna hijau-kuning khas corak Arab, Jawa, China dan Eropa. Di Pintu Masuk tertulis \"Pasarean Raja-Raja Sumenep di Asta Tinggi: 1. Pangeran Pulang Jiwa; 2. Pangeran Jimat; 3. Temenggung Tirtonegoro (Bindara Saod); 4. Panembahan Notokoeoemo (Mohammad Saleh)\". Lalu ada larangan untuk mengubah bentuk bangunan dan ditempati kuburan baru di ruangan kubah/serambi/pendopo.\r\n\r\nUntuk masuk ke Asta Tinggi tidak dipungut biaya apapun. Tetapi ada kotak amal untuk memberikan sejumlah infaq / shodaqoh. Untuk masuk ke Asta Tinggi, diharuskan melepas sepatu, menjaga wudhu dan niatkan berdoa kepada para raja. Nuansa ketika masuk ke Asta Tinggi juga terasa berbeda. Nuansanya seperti religi, tenang dan adem turut dirasakan.', 'Open 24 hours', 'https://www.google.com/maps/place/Soem%C3%AAn%C3%AAp+Vorstelijke+Begraafplaats/@-6.9966327,113.8347486,15z/data=!3m1!4b1!4m5!3m4!1s0x2dd9e66eadbeb745:0x34db7cc78ae901ad!8m2!3d-6.9966328!4d113.8435034'),
(5, 'Gili Iyang', 'giliIyang.jpg', 'giliIyang_L.jpg', 40000, 'Gili Iyang disebut sebagai tempat dengan oksigen terbaik kedua di dunia, setelah Laut Mati, Jordania. Juga sempat viral sebagai pulau awet muda.\r\n\r\nPada 2005, Lembaga Penerbangan dan Antariksa Nasional (LAPAN) melakukan penelitian. Seperti yang disampaikan Ahyak Ulumuddin, tour guide sekaligus Ketua Pokdarwis Gili Iyang.\r\n\r\nAda 17 tempat dalam penelitian selama 7 bulan itu. Hasilnya, kadar oksigen di Gili Iyang di atas rata-rata.\r\n\r\nRata-rata, kadar oksigen hanya 18-19 persen. Sementara di Gili Iyang, kadar oksigennya 20,9 persen pada siang hari dan 21 persen lebih pada malam hari.\r\n\r\nSehingga makin banyak yang datang ke Gili Iyang untuk wisata kesehatan. Terutama mereka yang menderita penyakit pernapasan seperti asma.', 'Open 24 hours', 'GiliIyang'),
(6, 'Goa Soekarno', 'goaSoekarno.jpg', 'goaSoekarno_L.jpg', 15000, 'Goa Soekarno merupakan sebuah bentuk kekaguman terhadap Presiden Pertama Indonesia yaitu Ir Soekarno. Goa yang berhiaskan gambar sang proklamator kemerdekaan tersebut dibangun sedemikian rupa sehingga tampak menarik dan indah. Tempat wisata ini sekarang merupakan salah satu destinasi wisata andalan sumenep. Goa ini memang sangat alami sekali jika anda masuk kedalam goa ini pasti akan dibuat takjub oleh keindahannya. Goa Soekarno memiliki beberapa celah untuk tempat masuknya sinar matahari ini tentunya akan membuat semakin cerah jika berada di dalam goa. Spot lubang ini biasanya sering digunakan sebagai spot untuk berfoto oleh para pengunjung.\r\n\r\nGoa Soekarno jika ditempuh dari pusat kota sumenep hanya berkisaran sekitar 45 menit saja dan tentunya akses untuk menuju ke tempat wisata baru ini cukup mudah. Mengenai fasilitas yang ada di tempat wisata ini sudah cukup lengkap dan dapat memuaskan para pengunjung. Harga tiket masuknya-pun cukup murah dan tentunya terjangkau bagi semua kalangan. Berlibur di Goa Soekarno bersama keluarga, sahabat, maupun orang tersayang tentunya akan membuat liburan anda semakin seru dan berkesan.', '08.00 – 17.00 WIB', 'GoaSoekarno'),
(7, 'Pantai Badur', 'pantaiBadur.jpg', 'pantaiBadur_L.jpg', 7000, 'Dari keindahan pesisir di wilayah Kabupaten Sumenep, pesisir Badur merupakan salah satu pantai atau pesisir yang menawarkan keindahan alam pantai. Pantai Badur, tidak jauh jaraknya antara Pantai Salopeng, di Kecamatan Salopeng yang terkenal dengan keindahan gunung pasirnya dengan Pantai Lombang, di Kecamatan Batangbatang yang juga dikenal dengan hutan pohon cemara udang dan pantainya yang landai.  Nama Badur tersebut di ambil dari nama desa yang ada di lokasi pantai tersebut, yaitu Desa Badur, kecamatan Batuputih, Kabupaten Sumenep, Madura, Jawa Timur.\r\n\r\nJarak antara pusat kota Sumenep dan Pantai Badur ini tidak terlalu jauh, meski juga tidak bisa dibilang dekat, kurang lebih sekitar 18 kilometer, jadi untuk sampai mungkin memakan waktu kurang lebih sekitar 30 hingga 35 menit dengan mobil. Pantai Badur adalah pantai yang indah, meski tidak seluas Pantai Slopeng dan Pantai Lombang, namun pantai ini memiliki ketertarikan tersendiri di mata masyarakat, apalagi pasirnya yang berwarna putih itu terlihat sangat cantik dibawah sinar matahari, pantai ini masih sangat bersih, mungkin karena masyarakat sekitar masih sangat menghargai betapa pentingnya kebersihan lingkungan.\r\n\r\nDi Pantai Badur Anda bisa menikmati keindahan pantai-pantai andalan Sumenep yaitu Lombang dan Slopeng, di sisi Timur Pantai Badur Anda bisa menikmati pesona Pantai Slopeng yang persis dengan Slopeng lengkap dengan gunungan pasirnya dan di daerah tengah Pantai Badur kita bisa menemukan pesona eksotika pantai Lombang yang hampir sama persis dengan Lombang lengkap dengan hamparan pasir yang luas dan cemara-cemara yang menghiasi dipinggirnya.\r\n\r\nPantai yang terletak di Kecamatan Batu Putih ini memiliki keistimewaan tersendiri. Di sisi barat pantai, mengalir air tawar yang membelah pasir putih. Air tawar itu bersambung dengan air laut. Di air tawar inilah anak-anak kecil biasa bermain. Para orangtua pun tidak perlu khawatir sebab belahan pasir yang menjadi tempat mengalirnya air tawar itu cukup dangkal. Sehingga, anak-anak kecil juga bisa menikmati indahnya bermain di pantai tanpa bahaya.\r\n\r\nKeindahan lain yang juga dimiliki Pantai Badur adalah batuan-batuan tinggi mirip gua. Para pengunjung biasanya mengambil gambar dari atas bebatuan sehingga terkesan seperti ada gabungan antara keindahan pegunungan dan pantai. Dari atas bebatuan ini Anda juga dapat menyaksikan indahnya senja. Saat sore hari, akan ada beberapa penduduk yang memang bermata pencaharian sebagai nelayan mulai bersiap-siap untuk pergi ke laut, kalau anda merasa tertarik anda bisa ikut pergi mencari ikan selagi diperbolehkan yang punya kapal, atau anda bisa menyewa kapal-kapal penduduk untuk bisa pergi memancing di laut beramai-ramai.', 'Open 24 hours', 'https://www.google.com/maps/place/BADUR+BEACH+(laut%2Btawar)/@-6.8807015,113.9713971,15z/data=!3m1!4b1!4m5!3m4!1s0x2dd9f22061199017:0x52c46cf32cd3f837!8m2!3d-6.8807016!4d113.9801519'),
(8, 'Pantai Ekasoghi', 'pantaiEkasoghi.jpg', 'pantaiEkasoghi_L.jpg', 10000, 'Pantai Ekasoghi menampilkan panorama berupa pantai, camping ground, dan hutan magrove yang sangat indah dan menakjubkan. Para pengunjung akan di ajak berkeliling mulai dari menjumpai Gazebo dan tempat berteduh yang berkonsep rumput ilalang. Hal menarik lainnya ialah dengan adanya Jembatan Jogging Track dengan panjang 400m yang terhubung ke lautan sehingga para pengunjung dapat melihat lautan dari area Jogging Track yang tersusun oleh susunan bambu yang dibuat mengelilingi hutan mangrove di area sekitar pantai.\r\n\r\nPada beberapa bagian baik bagian kiri dan kanan Jogging Track, para pengunjung akan menjumpai Gubuk kecil yang dapat digunakan untuk sekedar nongkrong, istirahat, bercanda tawa, dan menikmati keindahan dari Pantai e kasoghi. Sangat Eksotis sekali kan wisata yang satu ini.\r\n\r\nUntuk menuju kawasan wisata tersebut pengunjung dapat menempuh jarak kurang lebih 15km dari kota atau alun-alun Sumenep dengan jarak tempuh 20-30 menit berkendara. Lokasinya tersendiri berada di Dusun Nonggunong, Desa Tanjung, Kecamatan Saronggi, Kabupaten Sumenep, Jawa Timur.', '07.00 – 21.00 WIB', 'https://www.google.com/maps/place/Pantai+e+Kasoghi/@-7.1049289,113.8787736,15z/data=!3m1!4b1!4m5!3m4!1s0x2dd9e35fb92b229f:0x4b49326022c1ea9e!8m2!3d-7.104929!4d113.8875284'),
(9, 'Pantai Keris', 'pantaiKeris.jpg', 'pantaiKeris_L.jpg', 0, 'kota berjuluk ‘Kota Keris’ ini punya banyak potensi wisata alam dan pantai yang menarik dan menakjubkan. Mulai dari Pantai Lombang yang tersohor karena pohon cemara udangnya yang rimbun, hingga Pantai Slopeng karena bukit pasirnya. Selain itu, Sumenep juga punya hidden gem yang belum lama viral karena bentuknya yang unik. Surga tersembunyi itu berjuluk Pantai Keris.\r\n\r\nSesuai namanya, Pantai Keris adalah sebuah pantai yang bentuknya menyerupai keris atau lebih tepatnya sebuah pasir timbul yang memanjang ke arah laut. Panjang bentangan pasir ini sekitar 600 meter.\r\n\r\nBuat yang ingin wisata bebas keramaian, Pantai Keris bisa jadi tujuan. Tempatnya yang tersembunyi di balik puluhan tambak garam warga, membuat pantai ini serasa milik pribadi.\r\n\r\nSayangnya enggak ada tempat parkir khusus ntuk kamu yang membawa motor, sehingga wisatawan bermotor harus menitipkan motornya di rumah warga lalu berjalan kaki melewati jembatan bambu hingga puluhan tambak garam warga.\r\n\r\nNamun semua lelah terbayar ketika melihat keindahan Pantai Keris yang terbuka gratis untuk wisatawan.\r\n\r\nWaktu terbaik untuk ke Pantai Keris adalah pagi atau sore hari. Karena pantai ini enggak menyediakan tempat berteduh, sehingga kamu akan kepanasan kalau datang di siang hari.', 'Open 24 hours', 'https://www.google.com/maps/place/Pantai+Keris/@-7.045619,113.9506388,15z/data=!3m1!4b1!4m5!3m4!1s0x2dd9fd43b9466d45:0xe5c1cdbfa6085036!8m2!3d-7.0456191!4d113.9593936'),
(10, 'Hutan Mangrove', 'hutanMangrove.jpg', 'hutanMangrove_L.jpg', 10000, 'Sumenep memang kaya dengan potensi alam, termasuk hutan mangrove. Di desa Kebun Dadap Timur kecamatan Saronggi juga terdapat hutan mangrove yang cukup luas dan lebat. Lokasi ini baru saja dibuka sebagai destinasi wisata yang cukup menarik. Namanya Wisata Mangrove Kedatim (WMK).\r\n\r\nPengunjung bisa berjalan menyusuri hutan mangrove hingga 1 km. Pemandangan muara yang luas juga menjadi daya tarik tempat wisata ini. Setelah lelah berjlana-jalan menyusuri hutan bakau, pengunjung bisa bersantai di café di tengah hutan.\r\n\r\nSelain digunakan sebagai objek wisata alam, hutan mangrove yang disana digunakan sebagai tempat melestarikan berbagai jenis hutan mangrove dari oknum yang tidak bertanggung jawab, tak hanya itu kedepannya Hutan Wisata Mangrove Kedatim tengah mempersiapkan wisatanya untuk dijadikan wisata berbasis Edukasi Wisata untuk berbagai jenjang pendidikan.', '07.00 - 21.00 WIB', 'https://www.google.com/maps/place/Wisata+Mangrove+Kedatim/@-7.0934799,113.8557433,15z/data=!3m1!4b1!4m5!3m4!1s0x2dd9e3c79599d71b:0x4287239fd230d1b2!8m2!3d-7.09348!4d113.8644981'),
(11, 'Water Park Sumekar', 'waterPark.png', 'waterPark_L.png', 10000, 'Wisata air merupakan salah satu wisata favorit, termasuk juga berwisata ke Water Park Sumekar (WPS) yang menjadi salah satu wisata favorit di Sumenep Madura. Setiap harinya pasti saja ada pengunjung dan menjadi favorit akhir pekan terutama bagi para keluarga dan sikecil tersayang.\r\n\r\nWaterpark Sumekar adalah kolam pemandian yang dibuka untuk umum, letaknya pun tak jauh dari Kota Sumenep. Untuk menuju WPS, Anda cukup menuju arah barat diperempatan lampu merah setelah Taman Bunga Sumenep. Terus lurus lalu belok kiri dijembatan dan setelah itu kanan ke arah Asta Tinggi Sumenep.\r\n\r\nTepatnya lokasi wisata Water Park Sumekar terletak di Desa Kasengan, Kecamatan Manding, Sumenep. Sekitar 500 M sebelah barat Asta Tinggi Sumenep.\r\n\r\nWater park Sumekar tidak hanya menyediakan kolam renang anak, namun ada juga kolam renang untuk orang dewasa. Jadi selain cocok untuk anak-anak, WPS Sumenep juga cocok untuk orang dewasa.\r\n\r\nSelain berwisata air di water park, di area Water Park Sumekar terdapat juga “Mini Zoo” yang dihuni oleh banyak macam hewan seperi owa-owa, lutung, buaya, kuda, kanguru, ular, kijang, burung elang, burung kakak tua dan hewan-hewan langka lainnya.', '08.00 – 16.00 WIB', 'https://www.google.com/maps/place/Water+Park+Sumekar,+Kalebuan,+Kasengan,+Kec.+Manding,+Kabupaten+Sumenep,+Jawa+Timur+69452/@-6.9902443,113.8320677,15z/data=!3m1!4b1!4m5!3m4!1s0x2dd9e66c9cff9b0d:0x188985695c172682!8m2!3d-6.9905518!4d113.8408127'),
(12, 'Taman Tektona', 'tamanTektona.jpeg', 'tamanTektona_L.jpeg', 5000, 'Taman Tectona merupakan destinasi wisata yang beralamat di dusun larangan, Torbang, Kec. Batuan, Kabupaten Sumenep. Berada di pinggir jalan raya dan hanya berjarak 4 km dari pusat kota sumenep membuat taman tectona ini sangat mudah dikunjungi. Nama Tectona sendiri di ambil karena tempat ini di bangun di atas lahan yang di dominasi pohon jati, yang memiliki nama latin tectona grandis.\r\n\r\nTempat wisata yang mengusung konsep alam ini dikelilingi oleh banyak pohon sehingga memberi kesan asri dan sejuk hal ini cocok untuk kamu melepas penat dari lelahnya rutinitas sehari-hari. Terdapat banyak gazebo yangtersedia bisa kamu gunakan untuk sekedar duduk-duduk santai menikmati keindahan taman tectona. Ada banyak sport-sport berfoto untuk kamu yang suka berselfi ria bisa menambah koleksimu untuk di unggah di media social.', '07.00 – 22.00 WIB', 'https://www.google.com/maps/place/Wisata+Taman+Tectona/@-7.0152004,113.8076372,15z/data=!3m1!4b1!4m5!3m4!1s0x2dd9e6fc03cd6b1f:0xc36ab2cdc641889e!8m2!3d-7.0152005!4d113.816392'),
(13, 'Taman Adipura Sumenep', 'tamanBunga.jpg', 'tamanBunga_L.jpg', 0, 'Taman Adipura Sumenep atau masyarakat sekitar menyebutnya Taman Bunga atau TB merupakan destinasi taman yang tidak pernah sepi dari pengunjung. Bahkan, jangankan hari libur, hari biasa pun masih banyak pengunjung yang berdatangan ke destinasi. Ini membuktikan kalau Taman Adipura atau Taman Bunga memang benar-benar berkualitas.\r\n\r\nTaman Bunga ini bisa juga disebut sebagai alun-alun kota Sumenep karena memang lokasinya ada di tengah kota dan berada sejalan dengan Masjid Agung Sumenep serta Keraton Sumenep. Untuk masuk kesini, pengunjung sama sekali ngga dikenakan biaya alias gratis.\r\n\r\nTaman ini, akan semakin ramai saat malam tiba. Apabila pengunjung ingin mengajak  si kecil. Tidak perlu khawatir sebab terdapat pula berbagai jenis permainan yang sudah tersedia. Bagi Anda yang hobi kuliner, maka banyak pedagang yang menjual berbagai jenis camilan yang mengenyangkan.  Anda akan merasa senang dan betah di tempat wisata yang ramah anak.\r\n\r\nLiburan akan menjadi sangat berwarna dengan suasana  indah yang menyejukkan mata. Apalagi lokasinya yang dekat dengan masjid agung Sumenep.', 'Open 24 hours', 'https://www.google.com/maps/place/Taman+Adipura+Kota+Sumenep/@-7.0082693,113.851504,15z/data=!3m1!4b1!4m5!3m4!1s0x2dd9e42ac6da1bc7:0xdc14634f24fc149b!8m2!3d-7.0082694!4d113.8602588'),
(14, 'Keraton Sumenep', 'kraton.jpg', 'kraton_L.jpg', 4000, 'Pulau Madura yang mempunyai posisi geografis di Laut Jawa ini memang membuatnya menjadi memiliki banyak obyek wisata pantai. Namun tidak hanya pantainya saja yang wajib anda kunjungi saat anda pergi ke Madura, melainkan juga tempat yang satu ini yang patut anda datangi, yaitu Museum Keraton Sumenep di mana anda bisa menemukan berbagai benda peninggalan keraton di Sumenep.\r\n\r\nSeratus meter di sebelah timur Taman Adipura adalah lokasi Museum dan Keraton (Istana) Sumenep. Bangunan tua di sisi kanan jalan adalah tempat untuk menyimpan kereta emas, sebuah hadiah dari Ratu Inggris ke Raja Sumenep. Selain itu, juga digunakan untuk menjaga warisan lainnya; kursi tua, meja tua dan warisan lainnya.', '07.00 – 15.30 WIB', 'https://www.google.com/maps/place/Sumenep+Palace+Museum/@-7.0085114,113.8535412,15z/data=!3m1!4b1!4m5!3m4!1s0x2dd9e42b1170c777:0x392c4cc621a3b3cd!8m2!3d-7.0085189!4d113.8623317'),
(15, 'Pantai Lombang', 'pantaiLombang.jpg', 'pantaiLombang_L.jpg', 5000, 'Wisata Pantai Lombang Sumenep Madura adalah tempat wisata pantai bernilai sejarah yang ada di pulau Madura. Tempat ini cocok sebagai media berlibur dan belajar. Merasakan indahnya pantai sembari belajar sejarah Pantai Lombang di Sumenep Madura dan menambah ilmu pengetahuan alam. Anda yang berwisata beserta buah hati tercinta, Pantai Lombang ini salah satu lokasi yang tepat.\r\n\r\nPantai Lombang di Madura memiliki pantai dengan pasir putih dan air laut yang biru. Keunikan yang ada pada pantai ini adalah adanya pepohonan yang berjejer memagari pantai. Pohon yang tumbuh di area Pantai Lombang adalah pohon cemara udang. Pantai Lombang adalah satu-satunya pantai di Indonesia yang ditumbuhi oleh pohon cemara udang. Tidak seperti pohon cemara pada umumnya. Bila pohon cemara memiliki ketinggian yang menjulang dengan bentuk tegak dan tinggi, pohon cemara udang memiliki bentuk pohon yang agak rendah dan melengkunh seperti udang. Oleh sebab itu, pohon cemara jenis ini diberi nama pohon cemara udang. Pohon-pohon cemara tersebut menghilangkan kesan pantai yang biasanya panas. Udara yang mengalir dari pepohonan membuat suasana pantai ini terasa asri dan sejuk.\r\n\r\nPantai Lombang kabupaten Sumenep Jawa Timur Indonesia mempunyai panjang garis pantai hampir 12 kilometer. Keseluruhan bentangan pantai tersebut terisi oleh pasir putih. Terlihat elok dan menawan. Di tepi pantainya, dibangun beberapa bangunan kecil permanen yang bisa digunakan sebagai tempat beristrahat dan duduk-duduk bersama sambil menatap ombak dari kejauhan. Anda juga bisa menikmati bekal makanan atau minuman di tempat ini. Namun tetap saja, kebersihan adalah nomor satu. Jangan tinggalkan apapun di tempat ini kecuali jejak kaki Anda. Sebab, kebersihan pantai adalah tanggung jawab bersama, bukan hanya pengelola ataupun pengunjung saja. Selain duduk bersantai di tempat yang sudah disediakan, Anda bisa duduk langsung di atas pasir. Pasir-pasir yang berada di bawah pohon cemara, nyaman digunakan sebagai alas duduk. Anda juga bisa bermain membangun istana pasir dan aktivitas lainnya seperti menggambar, dan lain-lain. Jangan lupa untuk mengabadikan kenangan Anda di tempat ini dengan mengambil beberapa foto. Bila air laut dalam keadaan surut, Anda bisa melihat penampakan gurun pasir di pantai ini.', '07.00 – 18.00 WIB', 'https://www.google.com/maps/place/Pantai+Lombang/@-6.9178645,114.0475579,14z/data=!3m1!4b1!4m5!3m4!1s0x2dd9f7276ab8c685:0xe6566e3638889a6!8m2!3d-6.9155738!4d114.0586496');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `akun`
--
ALTER TABLE `akun`
  ADD PRIMARY KEY (`id`);

--
-- Indeks untuk tabel `wisata`
--
ALTER TABLE `wisata`
  ADD PRIMARY KEY (`kd_wisata`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `akun`
--
ALTER TABLE `akun`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=114;

--
-- AUTO_INCREMENT untuk tabel `wisata`
--
ALTER TABLE `wisata`
  MODIFY `kd_wisata` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
